#[repr(C, packed)]
#[derive(Default)]
pub struct TSS {
    _link: u16,
    _reserved0: u16,
    pub esp0: u32,
    pub ss0: u16,
    _reserved1: u16,
    esp1: u32,
    ss1: u16,
    _reserved2: u16,
    esp2: u32,
    ss2: u16,
    _reserved3: u16,
    _cr3: u32,
    _eip: u32,
    _eflags: u32,
    _eax: u32,
    _ecx: u32,
    _edx: u32,
    _ebx: u32,
    _esp: u32,
    _ebp: u32,
    _esi: u32,
    _edi: u32,
    es: u16,
    _es_reserved: u16,
    cs: u16,
    _cs_reserved: u16,
    ss: u16,
    _ss_reserved: u16,
    ds: u16,
    _ds_reserved: u16,
    fs: u16,
    _fs_reserved: u16,
    gs: u16,
    _gs_reserved: u16,
    _ldtr: u16,
    _ldtr_reserved: u16,
    _iopb_reserved: u16,
    iopb: u16,
    _ssp: u32,
}

impl TSS {
    pub const fn new() -> Self {
        Self {
            _link: 0,
            _reserved0: 0,
            esp0: 0,
            ss0: 0,
            _reserved1: 0,
            esp1: 0,
            ss1: 0,
            _reserved2: 0,
            esp2: 0,
            ss2: 0,
            _reserved3: 0,
            _cr3: 0,
            _eip: 0,
            _eflags: 0,
            _eax: 0,
            _ecx: 0,
            _edx: 0,
            _ebx: 0,
            _esp: 0,
            _ebp: 0,
            _esi: 0,
            _edi: 0,
            es: 0,
            _es_reserved: 0,
            cs: 0,
            _cs_reserved: 0,
            ss: 0,
            _ss_reserved: 0,
            ds: 0,
            _ds_reserved: 0,
            fs: 0,
            _fs_reserved: 0,
            gs: 0,
            _gs_reserved: 0,
            _ldtr: 0,
            _ldtr_reserved: 0,
            _iopb_reserved: 0,
            iopb: 0,
            _ssp: 0,
        }
    }

    pub fn init(&mut self, esp0: u32, data_segment: u16) {
        self.esp0 = esp0;
        self.ss0 = data_segment;
        self.iopb = core::mem::size_of::<TSS>() as u16;
    }
}
